[package]
name = "svrbsctl"
version = "0.2.0"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
btleplug = "0.9.0"
futures = "0.3.19"
thiserror = "1.0.30"
uuid = "0.8.2"

[dependencies.clap]
version = "3.0.7"
features = ["derive"]

[dependencies.tokio]
version = "1.15.0"
features = ["rt-multi-thread", "macros"]
