[package]
name = "svrbsctl"
version = "0.1.0"
authors = ["Andrew Gunnerson <chillermillerlong@hotmail.com>"]
edition = "2018"

[dependencies]
btleplug = "0.8.0"
clap = "3.0.0-beta.2"
futures = "0.3.16"
thiserror = "1.0.22"
uuid = "0.8.2"

[dependencies.tokio]
version = "1.9.0"
features = ["rt-multi-thread", "macros"]